config/routes.rb
TwelveStepper::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  scope "(:locale)", locale: /en|es|fr/ do

    get '/profile/edit', to: 'users#edit', as: "edit_profile"
    get '/profile/:username', to: 'users#show', as: :user_show
    resources :users, only: [:index, :new, :create, :update]
    patch '/entries/share/:id', to: 'entries#share_entry', as: "share_entry"
    resources :entries, except: :show

    get '/feed' => 'statuses#index', as: 'feed'
    resources :statuses, only: [:new, :create, :edit, :update, :destroy]

    patch '/worksheet_entries' => 'worksheet_entries#create'
    resources :worksheet_entries
    get '/login' => "sessions#new", as: "login"

    delete '/sessions', to: 'sessions#destroy'
    resources :sessions, only: [:new, :create, :destroy]

    get '/meetings/search' => "meetings#search_meetings", as: "search_meetings"
    resources :meetings, only: [:index, :search_meetings]

    namespace :big_book do
      get '/', to: 'chapters#index'
    end

    resources :friendships, only: [:index, :create]
    post '/friendships/accept/:id', to: 'friendships#update', as: :accept_friendship
    delete '/friendships/reject/:id', to: 'friendships#destroy', as: :reject_friendship
    delete '/friendships/remove/:id', to: 'friendships#destroy', as: :remove_friendship

    namespace :friends do
      resources :search, only: [:new, :create, :index]
    end

    namespace :api do
      namespace :v1 do

        namespace :entries do
          get '/search/:query', to: 'search#show'
        end

        namespace :worksheet do
          get '/entries', to: 'entries#index'
        end

        namespace :big_book do
          resources :chapters
          get '/search/:query', to: 'search#show'
        end

        namespace :feed do
          get '/statuses', to: 'statuses#index'
        end

      end
    end

    resources :help, only: :index
  end

  get "/pages/*id" => 'pages#show', as: :page, format: false

  get '/:locale', to: 'statuses#index'
  root 'statuses#index'

  get '/*not_found', to: 'not_found#index'
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :user

  def to_status
    (self.title.html_safe + " - " + self.body.html_safe).gsub(/(\<p\>|\<\/p\>)/, "").gsub("&#39;", "'")
  end

end

app/controllers/api/v1/entries/search_controller.rb
class Api::V1::Entries::SearchController < ApplicationController
  respond_to :json

  def show
    found = Entry.where(user_id: current_user.id).select do |record|
      record.body.downcase.include?(params[:query].to_s.downcase) ||
      record.title.downcase.include?(params[:query].to_s.downcase)
    end

    respond_with found
  end
  
end

app/controllers/api/v1/worksheet/entries_controller.rb
class Api::V1::Worksheet::EntriesController < ApplicationController
  respond_to :json

  def index
    entry = []
    step_id = params[:step] ? params[:step].to_i : nil
    if params[:section]
      worksheet = Worksheet.where(step: step_id, locale: I18n.locale.to_s).select{|s| s.title == params["section"]}.first
      entry = current_user.entries.where(step: step_id).select {|entry| entry.section == worksheet.title}.first
      package = {entry: entry, worksheet: worksheet, step: step_id, params: params}
    else
      entry = current_user.entries.where(step: step_id).first
      worksheet = Worksheet.where(step: step_id, locale: I18n.locale.to_s)
      package = {entry: entry, worksheet: worksheet, step: step_id, params: params}
    end

    respond_with package
  end

  def create
    respond_with params
  end



end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :authorize!

  def index
    @entries = current_user.entries
  end

  def new
    @entry = Entry.new
  end

  def create
    entry = Entry.new(entry_params)
    entry.update_attributes(user_id: current_user.id)

    if entry.save
      return share(entry) if params[:commit] == "Save and Share"
      flash[:notice] = t('flash.entry_save_success')
      redirect_to entries_path
    else
      flash[:notice] = t('flash.entry_save_failure')
      render :new
    end
  end

  def edit
    @entry = current_user.entries.where(id: params[:id]).first
    if @entry.section && @entry.step
      worksheets = Worksheet.where(step: @entry.step)
      @worksheet = worksheets.select {|worksheet| worksheet.title == @entry.section }.first
    end
  end

  def update
    entry = Entry.find(params[:id])
    entry.update_attributes(entry_params)
    if params[:commit] == "Save and Share" || params[:commit] == "Share"
      return share(entry)
    end
    redirect_to root_path
  end

  def destroy
    entry = Entry.find(params[:id])
    if entry.destroy
      flash[:notice] = t("flash.entry_delete_success")
      redirect_to entries_path
    else
      flash[:notice] = t("flash.entry_delete_failure")
      render :index
    end

  end

  def share_entry
    entry = current_user.entries.find(params[:id])
    return share(entry)
  end

  private

  def entry_params
    params.require(:entry).permit(:title, :body, :step, :section)
  end

  def share(entry)
    status = current_user.statuses.build(content: entry.to_status)
    if status.valid? && entry.valid?
      status.save
      entry.save
      flash[:notice] = t('flash.entry_share_success')
      redirect_to root_path
    else
      flash[:notice] = ("flash.entry_share_failure")
      redirect_to :back
    end
  end

end

app/views/entries/_entry.html.erb
<% cache entry do %>
  <div class="row" id="entry-index-item-row">

    <div class="col-md-3">

      <h4 class="entry-item-title"><%= link_to "#{entry.title}", edit_entry_path(entry.id) %></h4>
      <p class="entry-date"><%= entry.created_at.strftime("%m/%d/%Y") %></p>
      <% if entry.step.kind_of?(Fixnum) %>
        <p class="entry-step"><%= t("entries.step") %>: <%= entry.step %></p>
      <% end %>
    </div>

    <div class="col-md-7" id="entry-index-item-body">
      <%= entry.body.to_s.html_safe %>
    </div>

    <div class="col-md-2">
      <ul id="entry-item-actions">
        <li><%= link_to t('entries.edit'), edit_entry_path(entry.id) %></li>
        <li><%= link_to t('entries.delete'), entry_path(entry.id), method: :delete %></li>
        <li><%= link_to t('statuses.share'), share_entry_path(entry.id), method: 'patch' %></li>
      </ul>
    </div>

  </div>
<% end %>

app/views/entries/edit.html.erb
<div class="row page-header">
  <div class="col-md-3 my-journal-container">

    <% if @worksheet %>
      <h1 id="my-journal"><%= t('entries.work_step') %></h1>
    <% else %>
      <h1 id="my-journal"><%= t("entries.write") %></h1>
    <% end %>
  </div>
</div>
<div class='col-md-3 col-md-offset-2 pull-right'>

  <% if @worksheet %>
    <%= link_to t("entries.show_worksheet"), '#', id:'toggle-worksheet' %>

  <% end %>
</div>
<div class="entry-edit-container">
  <div id='entry-text-input'>
    <%= form_for @entry do |f| %>

      <p><%= f.text_field :title, :placeholder => t('entries.title'), id:'worksheet-entry-title' %></p>

      <%= f.cktext_area :body, :class => 'ckeditor' %>
      <br />
      <br />
      <div class="entry-link-container">
        <%= f.submit t('entries.create'), class:"btn-link entry-link-action", id:'worksheet-entry-submit' %>
        <%= link_to t('entries.delete'), entry_path(@entry.id), class:"btn-link entry-link-action", method: :delete %>
        <%= f.submit t('entries.save_and_share'), class:"btn-link entry-link-action" %>
      </div>

    <% end %>
  </div>
  <% if @worksheet %>
    <div class='hide-worksheet-details toggled-worksheet-details'>
      <h4><strong>Step <%= @worksheet.step %></strong> - <em><%= @worksheet.title %></em></h4>
      <div class='worksheet-body-details'>
        <%= @worksheet.body.html_safe %>
      </div>
    </div>
  <% end %>

 
 
  
</div>

app/views/entries/index.html.erb
<% cache :entries_index do %>
  <div class="row page-header">
      <div class="col-md-3 my-journal-container">
        <h1 id="my-journal"><%= link_to t('entries.my_journal'), entries_path %></h1>
      </div>
      <div class="col-md-4">
        <%= search_field 'entries_search', :meetings_search,  placeholder: t('meetings.search'), id:'entries-search' %>
      </div>
      <div class="col-md-3 col-md-offset-2" id="entry-index-actions">
        <%= link_to t("entries.work_step"), new_worksheet_entry_path, id: "work-a-step" %> 
        <%= link_to t("entries.write"), new_entry_path %>
      </div>
  </div>
<% end %>

<div id="entry-list-container">
  <% if @entries %>
    <%= render @entries %>
  <% else %>
    <p><%= t("entries.none") %></p>
  <% end %>
</div>

app/views/entries/new.html.erb
<div class="row page-header">
  <div class="col-md-7 my-journal-container">
    <h1 id="my-journal"><%= t('entries.write') %></h1>
  </div>
  <div class="col-md-3 col-md-offset-2" id="entry-index-actions">
    <%= link_to t("entries.work_step"), new_worksheet_entry_path, id: "work-a-step" %> 
  </div>
</div>
<br />
<div id="new-entry-container">
  <%= form_for @entry do |f| %>

    <p><%= f.text_field :title, :placeholder => t('entries.title') %></p>

    <p><%= f.cktext_area :body, :class => 'ckeditor' %></p>

    <br />
    <br />
    <div class="entry-link-container">
      <%= f.submit t('entries.create'), class:"btn-link entry-link-action", id:'entry-submit' %>
      <%= link_to t('entries.delete'), entries_path, class:"btn-link entry-link-action" %>
      <%= f.submit t('entries.share'), class:"btn-link entry-link-action" %>
    </div>  
  <% end %>
</div>