config/routes.rb
TwelveStepper::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  scope "(:locale)", locale: /en|es|fr/ do

    get '/profile/edit', to: 'users#edit', as: "edit_profile"
    get '/profile/:username', to: 'users#show', as: :user_show
    resources :users, only: [:index, :new, :create, :update]
    patch '/entries/share/:id', to: 'entries#share_entry', as: "share_entry"
    resources :entries, except: :show

    get '/feed' => 'statuses#index', as: 'feed'
    resources :statuses, only: [:new, :create, :edit, :update, :destroy]

    patch '/worksheet_entries' => 'worksheet_entries#create'
    resources :worksheet_entries
    get '/login' => "sessions#new", as: "login"

    delete '/sessions', to: 'sessions#destroy'
    resources :sessions, only: [:new, :create, :destroy]

    get '/meetings/search' => "meetings#search_meetings", as: "search_meetings"
    resources :meetings, only: [:index, :search_meetings]

    namespace :big_book do
      get '/', to: 'chapters#index'
    end

    resources :friendships, only: [:index, :create]
    post '/friendships/accept/:id', to: 'friendships#update', as: :accept_friendship
    delete '/friendships/reject/:id', to: 'friendships#destroy', as: :reject_friendship
    delete '/friendships/remove/:id', to: 'friendships#destroy', as: :remove_friendship

    namespace :friends do
      resources :search, only: [:new, :create, :index]
    end

    namespace :api do
      namespace :v1 do

        namespace :entries do
          get '/search/:query', to: 'search#show'
        end

        namespace :worksheet do
          get '/entries', to: 'entries#index'
        end

        namespace :big_book do
          resources :chapters
          get '/search/:query', to: 'search#show'
        end

        namespace :feed do
          get '/statuses', to: 'statuses#index'
        end

      end
    end

    resources :help, only: :index
  end

  get "/pages/*id" => 'pages#show', as: :page, format: false

  get '/:locale', to: 'statuses#index'
  root 'statuses#index'

  get '/*not_found', to: 'not_found#index'
end

app/controllers/api/v1/feed/statuses_controller.rb
class Api::V1::Feed::StatusesController < ApplicationController
  respond_to :json

  def index
    unless current_user
      render json: {}, :status => 404
    end

    sec = parse_time(params["time"])
    timestamp = Time.strptime(sec, '%s')
    puts timestamp
    statuses = []

    unless no_friends
      statuses << current_user.approved_friends.map do |friend|
        recent_statuses(friend, timestamp)
      end
    end

    found = StatusDecorator.decorate_collection(statuses.flatten.sort)

    respond_with found.map { |status| build_response_from_status(status) }
  end

  private

  def no_friends
    current_user.approved_friends.compact.empty?
  end

  def parse_time(time)
    (time.to_f / 1000).to_s
  end

  def recent_statuses(user, timestamp)
    user.statuses.where(updated_at: (timestamp.to_time)..(Time.now)).last(10)
  end

  def build_response_from_status(status)
    {posted_at: status.posted_time_ago,
     status: status,
     token: status.user.decorate.current_token_image_sm,
     user: status.user}
  end

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :authorize!, only: [:create, :edit, :update]

  def index
    return redirect_to login_path unless current_user
      
    @statuses = current_user.statuses.last(10)
    unless current_user.approved_friends.compact.empty?
      @statuses << current_user.approved_friends.map {|friend| friend.statuses.last(10)}
    end
    @statuses = StatusDecorator.decorate_collection(@statuses.flatten.sort)
    @status = current_user.statuses.new
  end

  def create
    @status = Status.new(user_id: current_user.id, content: params[:status][:content])
    if @status.save
      flash[:notice] = t('flash.status_save_success')
    else
      flash[:notice] = t('flash.status_save_failure')
    end
    redirect_to root_path
  end

  def edit
    authorize_status_user
  end

  def update
    authorize_status_user

    @status.update_attributes(content: params[:status][:content])
    if
      flash[:notice] = t('flash.status_update_success')
    else
      flash[:notice] = t('flash.status_save_failure')
    end
    redirect_to root_path
  end

  def destroy
    authorize_status_user
    if @status.destroy
      flash[:notice] = t('flash.status_delete_success')
    else
      flash[:notice] = t('flash.status_delete_failure')
    end
    redirect_to root_path
  end

  private

  def authorize_status_user
    @status = Status.find(params[:id]).decorate
    if @status.user != current_user
      flash[:notice] = t('flash.unauthorized')
      return redirect_to root_path
    end
  end

end

app/views/statuses/_status.html.erb
<div class="row status-item" id=<%= "status-#{status.id}" %>>
  <div class="col-md-3">
    <p><%= image_tag (status.user.decorate.current_token_image_sm), class: "status-token" %>
    <%= link_to status.user.username, user_show_path(status.user.username), class: "status-username" %></p>
    <p class="status-time"><%= status.posted_time_ago %></p>
  </div>
  <div class="col-md-9 status-content hide-status-content" id="status-content-<%= status.id %>" >
    <p><%= status.content.html_safe %></p>
  </div>
    <% if status.long? %>
      <div class="col-md-2 col-md-offset-3">
        <%= link_to t('entries.more'), '#', class:'toggle-status-content', id:"more-status-#{status.id}" %>
      </div>
    <% end %>

  <div class="col-md-2 col-md-offset-10">

    <% if current_user == status.user %>
      <%= link_to t("entries.edit"), edit_status_path(status), class: "edit-status-link" %>
      <%= link_to t("entries.delete"), status_path(status), method: :delete, class: "delete-status-link" %>
    <% end %>
  </div>

</div>

app/views/statuses/edit.html.erb
<div class="row">
  <div class="col-md-12" id="edit-status-title">
    <h1><%= t('statuses.editing') %></h1>
    <p class="status-time"><%= t("statuses.posted") + " " + @status.posted_time_ago %></p>
  </div>

  <div class="col-md-12" id="edit-status">
    <%= form_for @status do |f| %>
      <%= f.text_area :content, :placeholder => t('statuses.whats_up'), id: "edit-status-field" %>
      <br />
      <%= f.submit t("statuses.update"), id: "update-submit", class:"btn" %>
    <% end %>
  </div>
</div>

app/views/statuses/index.html.erb
<div class="row" id="friend-actions-bar">
  <div class="col-md-5">
    <h1><%= t('statuses.latest') %></h1>
  </div>
  <div class="col-md-7" id="friend-action-links">
    <%= link_to t("navbar.view_friends"), friendships_path, class:"action-link-item" %>
    <%= link_to t("navbar.find_friends"), new_friends_search_path, class:"action-link-item" %>
    <%= form_tag friends_search_index_path, id: "friend-search-form", method: :get, url: friends_search_index_path do %>
      <%= text_field_tag :user_search, params[:friend_name], :placeholder => "Search" %>
      <%= link_to image_tag('search_btn.png'), "#", :onclick => "$('#friend-search-form').submit()", id: 'user-search-submit' %>
    <% end %>
  </div>
</div>

<div class="row" id="new-status-container">
  <div class="col-md-3">
    <h3><%= t('statuses.mind') %></h3>
  </div>
  <div id="new-status-form" class="col-md-8">
    <%= form_for @status do |f| %>
      <%= f.text_area :content, :placeholder => t('statuses.whats_up'), id: "new-status-field" %>
  </div>
  <div class="col-md-1">
      <%= f.submit t("statuses.share"), class: "btn", id: "new-status-submit" %>
    <% end %>
  </div>
</div>

<div class="row">
  <div id="feed-activity" class="col-md-12">
    <%= render @statuses %>
  </div>
</div>