config/routes.rb
TwelveStepper::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  scope "(:locale)", locale: /en|es|fr/ do

    get '/profile/edit', to: 'users#edit', as: "edit_profile"
    get '/profile/:username', to: 'users#show', as: :user_show
    resources :users, only: [:index, :new, :create, :update]
    patch '/entries/share/:id', to: 'entries#share_entry', as: "share_entry"
    resources :entries, except: :show

    get '/feed' => 'statuses#index', as: 'feed'
    resources :statuses, only: [:new, :create, :edit, :update, :destroy]

    patch '/worksheet_entries' => 'worksheet_entries#create'
    resources :worksheet_entries
    get '/login' => "sessions#new", as: "login"

    delete '/sessions', to: 'sessions#destroy'
    resources :sessions, only: [:new, :create, :destroy]

    get '/meetings/search' => "meetings#search_meetings", as: "search_meetings"
    resources :meetings, only: [:index, :search_meetings]

    namespace :big_book do
      get '/', to: 'chapters#index'
    end

    resources :friendships, only: [:index, :create]
    post '/friendships/accept/:id', to: 'friendships#update', as: :accept_friendship
    delete '/friendships/reject/:id', to: 'friendships#destroy', as: :reject_friendship
    delete '/friendships/remove/:id', to: 'friendships#destroy', as: :remove_friendship

    namespace :friends do
      resources :search, only: [:new, :create, :index]
    end

    namespace :api do
      namespace :v1 do

        namespace :entries do
          get '/search/:query', to: 'search#show'
        end

        namespace :worksheet do
          get '/entries', to: 'entries#index'
        end

        namespace :big_book do
          resources :chapters
          get '/search/:query', to: 'search#show'
        end

        namespace :feed do
          get '/statuses', to: 'statuses#index'
        end

      end
    end

    resources :help, only: :index
  end

  get "/pages/*id" => 'pages#show', as: :page, format: false

  get '/:locale', to: 'statuses#index'
  root 'statuses#index'

  get '/*not_found', to: 'not_found#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  include InvalidatesCache unless ENV['TRAVIS']
  has_secure_password

  validates :username, :email, :last_drink, presence: true
  validates_uniqueness_of :username, :email

  validates_date :last_drink, :after => lambda { 100.years.ago }

  has_many :entries
  has_many :statuses

  has_many :friendships, dependent: :destroy
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id", dependent: :destroy

  has_many :friends, through: :friendships
  has_many :inverse_friends, through: :inverse_friendships, source: :user


  def days_sober
    diff = Time.now - last_drink.to_time
    return 1 if diff < 86400
    diff.to_i / 86400
  end

  def approved_friends
    return calculate_approved_friends if ENV['TRAVIS']

    Rails.cache.fetch("approved_friends_for_#{self.username}") do
      calculate_approved_friends
    end
  end

  def pending_friends
    return calculate_pending_friends if ENV['TRAVIS']

    Rails.cache.fetch("pending_friends_for_#{self.username}") do
      calculate_pending_friends
    end
  end

  def all_friendships_and_inverse_friendships
    self.friendships + self.inverse_friendships
  end

  def all_friends_and_inverse_friends
    result = []
    result += self.friendships.map { |f| f.friend }
    result += self.inverse_friendships.map { |f| f.user }
    result
  end

  def is_friends_with?(other)
    self == other || self.approved_friends.include?(other)
  end

  def friend_or_pending_with?(other)
    self == other || self.all_friends_and_inverse_friends.include?(other)
  end

  private

  def calculate_approved_friends
    friends = []
    friends += self.friendships.approved.where(user_id: id).map {|friendship| friendship.friend}
    friends += self.inverse_friendships.approved.where(friend_id: id).map {|friendship| friendship.user}
    friends
  end

  def calculate_pending_friends
    friends = []
    friends += self.friendships.pending.where(user_id: id).map {|friendship| friendship.friend}
    friends += self.inverse_friendships.pending.where(friend_id: id).map {|friendship| friendship.user}
    friends
  end
end

app/controllers/api/v1/users/search_controller.rb
class Api::V1::Users::SearchController < ApplicationController
  respond_to :json

  def show
    found = User.where(username: params[:query].gsub("@", ""))

    names = found.pluck(:username)
    response = names.empty? ? 404 : names.to_json
    respond_with response
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize!, except: [:index, :create, :show]

  def index
    redirect_to login_path(locale: params[:locale])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.update_attributes(locale: params[:locale])
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = t("flash.account_create_success")
      redirect_to help_index_path
    else
      render "sessions/new", :layout => "landing"
    end
  end

  def show
    @user = User.find_by(username: params[:username]).decorate
    if current_user.is_friends_with?(@user)
      @statuses = StatusDecorator.decorate_collection(@user.statuses.take(30))
    end
  end

  def update
    I18n.locale = params[:user][:locale]
    current_user.update(user_params)
    if current_user.save
      flash[:notice] = t("flash.account_update_success")
    else
      flash[:notice] = t("flash.account_update_failure")
    end
    redirect_to edit_profile_path
  end

  def edit
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :bio, :password, :password_confirmation, :locale, :last_drink)
  end

end

app/helpers/users_helper.rb
module UsersHelper
  

  
end

app/views/users/_new.html.erb
<%= form_for @user, url: users_path, method: :post do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, t("flash.error")) %>
          <%= " " + t('flash.prohibited_save') + ": " %></h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-md-5">
    <div class="actions" id="get-started">
      <strong><%= t("profile.get_started") %></strong>
    </div>
    <div class="field">
      <%= f.text_field :username, :placeholder => t("profile.username"), :tabindex => 1 %>
    </div>
    <div class="field">
      <%= f.text_field :email, :placeholder => t("profile.email"), :tabindex => 2 %>
    </div><br />
    <div class="actions" id="last-drink-selector">
      <p><%= t("profile.last_drink") %></p>
      <%= f.date_field :last_drink, :tabindex => 5 %>
    </div>
  </div>

  <div class="col-md-4" id="right-login-column">
    <div class="field">
      <%= f.password_field :password, id: "new_password" %>
      <%= text_field_tag :new_fake_password, params[:new_fake_password], {:placeholder => t("profile.password"), :tabindex => 3} %>
    </div>
    <div class="field">
      <%= text_field_tag :new_fake_password_confirmation, params[:new_fake_password_confirmation], {:placeholder => t("profile.password_confirmation")} %>
      <%= f.password_field :password_confirmation, id: "new_password_confirmation", :tabindex => 4 %>
    </div><br />
    <div class="actions col-md-12" id="sign-up">
      <%= f.submit t("profile.create_account"), class: "btn-link", :tabindex => 6 %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="row page-header">
  <div class="col-md-8">
    <div id="profile-edit"><br />
      <%= form_for current_user, method: :patch, url: user_path(current_user.id) do |f| %>
        <h2><%= t('profile.details') %></h2>

        <p><%= f.label :username, t("profile.username") %></p>
        <p><%= f.text_field :username %></p>

        <p><%= f.label :email, t("profile.email") %></p>
        <p><%= f.text_field :email %></p>

        <p><%= f.label :bio, t("profile.bio") %></p>
        <p><%= f.text_area :bio %></p>

        <p><%= f.label :password, t("profile.password") %></p>
        <p><%= f.password_field :password %></p>

        <p><%= f.label :password_confirmation, t("profile.password_confirmation") %></p>
        <p><%= f.password_field :password_confirmation %></p>

        <p><%= f.label :locale, t("profile.language") + ":" %><%= f.select :locale, [:en, :es, :fr] %></p><br />

        <p><%= f.label :last_drink, t("profile.change") + ": " %></p>
        <p><%= f.date_field :last_drink, id: "datepicker" %></p>

        <%= f.submit t("profile.update"), class: "btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div id="user-details" class="row">
  <div class="col-md-3">
    <h1><%= image_tag(@user.current_token_image) %>
    <%= @user.username %></h1>
    <p><%= @user.days_sober %></p>
  </div>
  <div class="col-md-7" id="user-bio">
    <% unless @user.bio == "" %>
      <p><strong><%= t("profile.bio") + ": " %></strong></p>
      <p><%= @user.bio %></p>
    <% end %>
  </div>
  <div class="col-md-2" id="user-show-actions">
    <% unless current_user.friend_or_pending_with?(@user) %>
      <%= form_for Friendship.new, method: :create, url: friendships_path do |f| %>
        <%= f.hidden_field :user_id, value: @user.id %>
        <h3><%= f.submit t("friendships.add_friend"), id: "#{@user.username}-submit", class: 'btn' %></h3>
      <% end %>
    <% end %>

    <% if current_user == @user %>
      <h3><%= link_to t("profile.edit"), edit_profile_path, class: 'btn' %></h3>
    <% end %>
  </div>
</div>

<% if current_user.is_friends_with?(@user) %>
  <div id="recent-activity">
    <h3><%= @user.username + "'s " + t("profile.recent_activity") %></h3>
    <%= render @statuses %>
  </div>
<% end %>