config/routes.rb
TwelveStepper::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  scope "(:locale)", locale: /en|es|fr/ do

    get '/profile/edit', to: 'users#edit', as: "edit_profile"
    get '/profile/:username', to: 'users#show', as: :user_show
    resources :users, only: [:index, :new, :create, :update]
    patch '/entries/share/:id', to: 'entries#share_entry', as: "share_entry"
    resources :entries, except: :show

    get '/feed' => 'statuses#index', as: 'feed'
    resources :statuses, only: [:new, :create, :edit, :update, :destroy]

    patch '/worksheet_entries' => 'worksheet_entries#create'
    resources :worksheet_entries
    get '/login' => "sessions#new", as: "login"

    delete '/sessions', to: 'sessions#destroy'
    resources :sessions, only: [:new, :create, :destroy]

    get '/meetings/search' => "meetings#search_meetings", as: "search_meetings"
    resources :meetings, only: [:index, :search_meetings]

    namespace :big_book do
      get '/', to: 'chapters#index'
    end

    resources :friendships, only: [:index, :create]
    post '/friendships/accept/:id', to: 'friendships#update', as: :accept_friendship
    delete '/friendships/reject/:id', to: 'friendships#destroy', as: :reject_friendship
    delete '/friendships/remove/:id', to: 'friendships#destroy', as: :remove_friendship

    namespace :friends do
      resources :search, only: [:new, :create, :index]
    end

    namespace :api do
      namespace :v1 do

        namespace :entries do
          get '/search/:query', to: 'search#show'
        end

        namespace :worksheet do
          get '/entries', to: 'entries#index'
        end

        namespace :big_book do
          resources :chapters
          get '/search/:query', to: 'search#show'
        end

        namespace :feed do
          get '/statuses', to: 'statuses#index'
        end

      end
    end

    resources :help, only: :index
  end

  get "/pages/*id" => 'pages#show', as: :page, format: false

  get '/:locale', to: 'statuses#index'
  root 'statuses#index'

  get '/*not_found', to: 'not_found#index'
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  include InvalidatesCache unless ENV['TRAVIS']
  validates_presence_of :user_id, :friend_id, :status
  validates_inclusion_of :status, in: %w(pending approved)
  belongs_to :user
  belongs_to :friend, class_name: "User"

  scope :pending, -> { where(status: "pending") }
  scope :approved, -> { where(status: "approved") }

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def index
    @friendships = current_user.friendships.approved
    @inverse_friendships = current_user.inverse_friendships.approved
    @pending = current_user.inverse_friendships.pending
  end

  def create
    other = User.find(params[:friendship][:user_id])
    unless current_user.friend_or_pending_with?(other)

      @friendship = current_user.friendships.new
      @friendship.update_attributes(status: 'pending', friend_id: params[:friendship][:user_id])
      if @friendship.save
        flash.notice = t("flash.friend_request_sent")
      end

    else
      flash.notice = t("flash.friend_request_failed")
    end
    redirect_to new_friends_search_path
  end

  def update
    @friendship = current_user.inverse_friendships.find(params[:id])
    @friendship.update_attributes(status: "approved")
    flash[:notice] = t("flash.friendship_approved") + " " + @friendship.user.username + "."
    redirect_to :back
  end

  def destroy
    begin
      @friendship = current_user.inverse_friendships.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      @friendship = current_user.friendships.find(params[:id])
    end
    @friendship.destroy
    flash[:notice] = t("flash.friendship_rejected")
    redirect_to :back
  end

  def remove
  end

end

app/views/friendships/_friendship.html.erb
<div class="row current-friend" id=<%= "friend-#{friendship.friend.username}"%>>
  <div class="col-md-2">
    <p class="current-friend-details"><%= image_tag (friendship.friend.decorate.current_token_image_sm), class: "status-token" %>
    <%= link_to friendship.friend.username, user_show_path(friendship.friend.username), class: "friend-name-link" %></p>
  </div>
  <div class="col-md-8">
    <%= t('profile.bio') + ": " + friendship.friend.bio %>
  </div>
  <div class="col-md-2 current-friend-actions">
    <%= link_to t("friendships.view_profile"), user_show_path(friendship.friend.username), class: "btn-link" %>
    <br />
    <br />
    <%= button_to t("friendships.remove"), remove_friendship_path(friendship.id), method: :delete, class: 'btn-link' %>
  </div>
</div>

app/views/friendships/_inverse_friendship.html.erb
<div class="row current-friend" id=<%= "friend-#{inverse_friendship.user.username}"%>>
  <div class="col-md-2">
    <p class="current-friend-details"><%= image_tag (inverse_friendship.user.decorate.current_token_image_sm), class: "status-token" %>
    <%= link_to inverse_friendship.user.username, user_show_path(inverse_friendship.user.username), class: "friend-name-link" %></p>
  </div>
  <div class="col-md-8">
    <%= t('profile.bio') + ": " + inverse_friendship.user.bio %>
  </div>
  <div class="col-md-2 current-friend-actions">
    <%= link_to t("friendships.view_profile"), user_show_path(inverse_friendship.user.username), class: "btn-link" %>
    <br />
    <br />
    <%= button_to t("friendships.remove"), remove_friendship_path(inverse_friendship.id), method: :delete, class: 'btn-link' %>
  </div>
</div>

app/views/friendships/_pending_friendship.html.erb
<div class="row pending-friendship" id=<%= "friend-#{friendship.friend.username}"%>>
  <div class="col-md-2">
    <p class="pending-details"><%= image_tag (friendship.friend.decorate.current_token_image_sm), class: "status-token" %>
    <%= link_to friendship.friend.username, user_show_path(friendship.friend.username), class: "friend-name-link" %></p>
  </div>
  <div class="col-md-8">
    <%= t('profile.bio') + ": " + friendship.friend.bio %>
  </div>
  <div class="col-md-2 pending-actions">
    <%= link_to t("friendships.view_profile"), user_show_path(friendship.friend.username), class: 'btn-link' %></p>
    <%= button_to t("friendships.cancel"), remove_friendship_path(friendship.id), method: :delete, class: 'btn-link' %>
  </div>
</div>

app/views/friendships/_pending_inverse_friendship.html.erb
<div class="row pending-friend" id=<%= "pending-#{inverse_friendship.user.username}"%>>
  <div class="col-md-2">
    <p class="current-friend-details"><%= image_tag (inverse_friendship.user.decorate.current_token_image_sm), class: "status-token" %>
    <%= link_to inverse_friendship.user.username, user_show_path(inverse_friendship.user.username), class: "friend-name-link" %></p>
  </div>
  <div class="col-md-8">
    <p><%= t('profile.bio') + ": " + inverse_friendship.user.bio %></p>
  </div>
  <div class="col-md-2 pending-friend-actions">
    <%= button_to t("friendships.accept"), accept_friendship_path(inverse_friendship.id), class: 'btn-link' %>
    <br />
    <%= button_to t("friendships.reject"), reject_friendship_path(inverse_friendship.id), method: :delete, class: 'btn-link', id:"remove-pending-friendship" %>
  </div>
</div>

app/views/friendships/index.html.erb
<div class="row" id="view-friends-index">
  <div class="col-md-12" id="view-friends-index-title">
    <h1><%= t("friendships.my_friends") %></h1>
  </div>
</div>

<%= render partial: 'friendship', collection: @friendships %>
<%= render partial: 'inverse_friendship', collection: @inverse_friendships %>

<div id="pending-friendships" class="row">
  <div class="col-md-12" id="friend-requests-title">
    <h2><%= t("friendships.friend_requests") %></h2>
  </div>
</div>
<%= render partial: 'pending_inverse_friendship', collection: @pending, as: :inverse_friendship %>